import type { GeneratorCreativeType, GeneratorPlatform, MarketingGoal } from "@/features/campaign-generator/types/campaign-generator.types";

export const SUPPORTED_GENERATOR_PLATFORMS: GeneratorPlatform[] = ["META"];
export const MARKETING_GOAL_OPTIONS: MarketingGoal[] = ["AWARENESS", "TRAFFIC", "SALES", "ENGAGEMENT", "LEADS"];
export const CREATIVE_TYPE_OPTIONS: GeneratorCreativeType[] = [
  "IMAGE",
  "VIDEO",
  "CAROUSEL",
  "COLLECTION",
  "SLIDESHOW",
  "STORY",
  "MESSAGE",
  "INTERACTIVE",
  "PLAYABLE",
  "AUDIO",
  "TEXT",
  "HTML5",
];

export const CURRENCY_OPTIONS = [
  "USD",
  "EUR",
  "GBP",
  "AUD",
  "CAD",
  "JPY",
  "CNY",
  "INR",
  "BRL",
  "MXN",
  "KRW",
  "SGD",
  "NZD",
  "CHF",
  "SEK",
  "NOK",
  "DKK",
  "PLN",
  "TRY",
  "RUB",
  "ZAR",
  "HKD",
  "TWD",
  "THB",
  "VND",
  "IDR",
  "MYR",
  "PHP",
  "AED",
  "SAR",
] as const;

export const CALL_TO_ACTION_OPTIONS = [
  "LEARN_MORE",
  "SHOP_NOW",
  "DOWNLOAD",
  "SIGN_UP",
  "CONTACT_US",
  "BOOK_NOW",
  "GET_OFFER",
  "GET_QUOTE",
  "GET_STARTED",
  "INSTALL_APP",
  "LISTEN",
  "ORDER_NOW",
  "PLAY_GAME",
  "REGISTER_NOW",
  "RENT_NOW",
  "SEE_MORE",
  "SEND_EMAIL",
  "SEND_MESSAGE",
  "SEND_WHATSAPP",
  "SUBSCRIBE",
  "VISIT_SITE",
  "WATCH_MORE",
  "WATCH_NOW",
  "YES",
] as const;
