export const QUERY_KEYS = {
  AUTH_ME: ["auth", "me"] as const,
  DASHBOARD: ["dashboard"] as const,
  CAMPAIGNS: ["campaigns"] as const,
  CAMPAIGN_DETAILS: ["campaigns", "details"] as const,
  AD_ACCOUNTS: ["ad-accounts"] as const,
  PUBLISHER: ["publisher"] as const,
  SYNCHRONIZATION: ["synchronization"] as const,
  AUTOMATION_RUNS: ["automation", "runs"] as const,
  SHOPIFY: ["shopify"] as const,
  META_CONNECTION: ["meta", "connection"] as const,
  META_BUSINESSES: ["meta", "businesses"] as const,
  META_AD_ACCOUNTS: ["meta", "ad-accounts"] as const,
  META_PAGES: ["meta", "pages"] as const,
  META_INSTAGRAM_ACCOUNTS: ["meta", "instagram-accounts"] as const,
  META_PIXELS: ["meta", "pixels"] as const,
  META_CATALOGS: ["meta", "catalogs"] as const,
  STORES: ["stores"] as const,
  STORE_PRODUCTS: ["stores", "products"] as const,
  AI_SESSIONS: ["ai-sessions"] as const,
  ORGANIZATIONS: ["organizations"] as const,
  SETTINGS: ["settings"] as const,
  ANALYTICS: ["analytics"] as const,
} as const;
