export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  UNAUTHORIZED: "/unauthorized",
  FORBIDDEN: "/forbidden",
  DASHBOARD: "/dashboard",
  CAMPAIGNS: "/campaigns",
  CAMPAIGN_DETAILS: (id: string) => `/campaigns/${id}`,
  AD_SETS: "/ad-sets",
  ADS: "/ads",
  CREATIVES: "/creatives",
  CREATIVE_ASSETS: "/creative-assets",
  STORAGE: "/storage",
  CAMPAIGN_GENERATOR: "/campaign-generator",
  AI_COPY: "/ai-copy",
  PUBLISHER: "/publisher",
  SYNCHRONIZATION: "/synchronization",
  AUTOMATION_PIPELINES: "/automation/pipelines",
  AUTOMATION_PIPELINE_DETAILS: (id: string) => `/automation/pipelines/${id}`,
  AUTOMATION_RUNS: "/automation/runs",
  AUTOMATION_RUN_DETAILS: (id: string) => `/automation/runs/${id}`,
  AUTOMATION_WORKFLOWS: "/automation/workflows",
  ANALYTICS: "/analytics",
  ANALYTICS_DETAILS: (id: string) => `/analytics/${id}`,
  REPORTS: "/reports",
  SHOPIFY: "/shopify",
  SHOPIFY_CONNECTIONS: "/shopify/connections",
  SHOPIFY_DETAILS: "/shopify/details",
  PLATFORM_CONNECTIONS: "/platform-connections",
  PLATFORM_CREDENTIALS: "/platform-credentials",
  AD_ACCOUNTS: "/ad-accounts",
  ORGANIZATION: "/organization",
  MEMBERS: "/members",
  INVITATIONS: "/invitations",
  MEMBERSHIPS: "/memberships",
  PROFILE: "/profile",
  SETTINGS: "/settings",
} as const;

export const PUBLIC_ROUTES = [ROUTES.LOGIN, ROUTES.REGISTER, ROUTES.UNAUTHORIZED];
