export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  UNAUTHORIZED: "/unauthorized",
  FORBIDDEN: "/forbidden",
  DASHBOARD: "/dashboard",
  PRODUCTS: "/products",
  CAMPAIGNS: "/campaigns",
  CAMPAIGN_DETAILS: (id: string) => `/campaigns/${id}`,
  AI_SESSIONS: "/ai-sessions",
  AI_SESSION_DETAILS: (id: string) => `/ai-sessions/${id}`,
  ANALYTICS: "/analytics",
  ANALYTICS_DETAILS: (id: string) => `/analytics/${id}`,
  SHOPIFY: "/shopify",
  SHOPIFY_CONNECTIONS: "/shopify/connections",
  SHOPIFY_DETAILS: "/shopify/details",
  ADVERTISING_CONFIGURATION: "/advertising",
  ORGANIZATION: "/organization",
  MEMBERS: "/members",
  INVITATIONS: "/invitations",
  PROFILE: "/profile",
  SETTINGS: "/settings",

  /**
   * @deprecated Legacy Advertising OS routes — pages return 404.
   * Kept temporarily for deep-link compatibility until Phase 10 cleanup.
   */
  AD_SETS: "/ad-sets",
  ADS: "/ads",
  CREATIVES: "/creatives",
  CREATIVE_ASSETS: "/creative-assets",
  STORAGE: "/storage",
  CAMPAIGN_GENERATOR: "/campaign-generator",
  AI_COPY: "/ai-copy",
  PUBLISHER: "/publisher",
  SYNCHRONIZATION: "/synchronization",
  AUTOMATION_PIPELINES: "/automation/pipelines",
  AUTOMATION_PIPELINE_DETAILS: (id: string) => `/automation/pipelines/${id}`,
  AUTOMATION_RUNS: "/automation/runs",
  AUTOMATION_RUN_DETAILS: (id: string) => `/automation/runs/${id}`,
  AUTOMATION_WORKFLOWS: "/automation/workflows",
  REPORTS: "/reports",
  PLATFORM_CONNECTIONS: "/platform-connections",
  PLATFORM_CREDENTIALS: "/platform-credentials",
  AD_ACCOUNTS: "/ad-accounts",
  MEMBERSHIPS: "/memberships",
} as const;

export const PUBLIC_ROUTES = [ROUTES.LOGIN, ROUTES.REGISTER, ROUTES.UNAUTHORIZED];
