import { PromptTemplate } from '../../ai/interfaces/prompt.interfaces';
import { MARKETING_COPY_PROMPT_TEMPLATE_ID } from '../constants/ai-copy.constants';

export const MARKETING_COPY_PROMPT_TEMPLATE: PromptTemplate = {
  id: MARKETING_COPY_PROMPT_TEMPLATE_ID,
  description:
    'Generate performance marketing copy for an ad creative from product and campaign context.',
  systemPrompt: [
    'You are an expert performance marketing copywriter.',
    'Write concise, conversion-focused advertising copy.',
    'Respect platform norms and the requested language/country context.',
    'Do not invent false product claims.',
    'Return only valid JSON matching the required schema.',
    'Do not wrap the response in markdown fences.',
  ].join(' '),
  userPromptTemplate: [
    'Generate marketing copy for the following advertising creative.',
    '',
    '## Campaign',
    '- ID: {{campaignId}}',
    '- Name: {{campaignName}}',
    '- Objective: {{campaignObjective}}',
    '- Platform: {{platform}}',
    '',
    '## Creative',
    '- ID: {{creativeId}}',
    '- Name: {{creativeName}}',
    '- Type: {{creativeType}}',
    '- Country: {{country}}',
    '- Language: {{language}}',
    '- Landing page: {{landingPageUrl}}',
    '',
    '## Shopify Product',
    '- ID: {{productId}}',
    '- Title: {{productTitle}}',
    '- Vendor: {{productVendor}}',
    '- Product type: {{productType}}',
    '- Tags: {{productTags}}',
    '- Description: {{productDescription}}',
    '- Featured image: {{featuredImageUrl}}',
    '- Image URLs: {{imageUrls}}',
    '- Variants: {{variantTitles}}',
    '',
    '## Required JSON fields',
    '- primaryText (string)',
    '- headline (string)',
    '- description (string)',
    '- cta (string, human-readable call to action)',
    '- ctaEnum (one of: SHOP_NOW, LEARN_MORE, ORDER_NOW, GET_OFFER, SIGN_UP, SEE_MORE, VISIT_SITE)',
    '- suggestedHook (string)',
    '- painPoints (string[])',
    '- benefits (string[])',
    '- targetAudienceSummary (string)',
    '- offerAngle (string)',
    '- marketingAngle (string)',
    '- platformNotes (string)',
    '- tone (string)',
  ].join('\n'),
};
