export const FEATURE_MODULES = [
  "auth",
  "dashboard",
  "campaigns",
  "ad-sets",
  "ads",
  "creatives",
  "creative-assets",
  "storage",
  "campaign-generator",
  "ai-copy",
  "publisher",
  "synchronization",
  "automation",
  "analytics",
  "reporting",
  "shopify",
  "platform-connections",
  "platform-credentials",
  "ad-accounts",
  "organizations",
  "memberships",
  "invitations",
  "users",
  "settings",
] as const;
